---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rafael345/staging.floricelonline.com/wp-content
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R languages $DEPLOYPATH/
    - /bin/cp -R plugins $DEPLOYPATH/
    - /bin/cp -R themes $DEPLOYPATH/
    - /bin/cp -R uploads $DEPLOYPATH/
